### ISSUE TITLE
Support setting persistent volume reclaim policy

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#103]
**Is your feature request related to a problem? Please describe.**
persistentVolumeReclaimPolicy isn't an option under PersistentVolumeClaimSpec v1 core I would like to be able to set it to "Delete" for our solrcloud test pipelines where I don't want the PVCs sticking around after deletion.

What would it take to be able set different values for persistentVolumeReclaimPolicy?

Do we need orphan pvc cleanup code logic like I see in zookeeper-operator? Or will just setting this do the cleanup for us?

**Describe the solution you'd like**
Ability to configure under dataPvcSpec "Delete" for persistentVolumeReclaimPolicy

**Describe alternatives you've considered**
In the meantime ill write a cleanup script outside of operator in our pipeline.

**Comment by HoustonPutman** [comment]
@sepulworld This is definitely a feature we need to add.

Unless I'm misunderstanding, I am pretty sure that the reclaimPolicy is a feature of the PersistentVolume, not the PVC. It says if the PV is unmapped from the PVC, what should happen to it. The only way that the solr operator could use this is for users to specify that they want a certain reclaim policy for their PVs by specifying it in the storageClass parameter of their pvcSpec.

What we need to do is delete PVCs after the statefulSet has been deleted. This would require using the finalizers much like the Zookeeper Operator does. I think following their lead would be good here. I think this is also an opportunity to refactor how we want the spec to look for this. Since we will have to create a new `persistence` option (or another name) that the `pvcSpec` and `deletionPolicy` will live under. We can make this backwards compatible at least for a minor version. But we will have to move things around eventually.

**Comment by sepulworld** [comment]
The finalizer makes sense!

**Comment by HoustonPutman** [comment]
I think we need an overhaul of the storage settings.

Something that looks like:

```yaml
Spec:
    storage:
        storageType: <ephemeral,persistent>
        persistence:
            pvcSpec: <PVCSpec object>
            reclaimPolicy: <Reclaim,Delete>
         ephemeral:
            emptyDirVolumeSource: <EmptyDirVolumeSource object>
```

This is very similar (if not exactly the same as) the options soon to be in the Zookeeper Operator. Maybe we rename to dataStorage just to make sure that it's separate from the backupRestoreVolume stuff. Or maybe that moves into this section? Definitely some options to think about.

**Comment by sepulworld** [comment]
@swarupdonepudi was looking into this. We have to manually or script the cleanup of PVCs presently. Would be sweet to build in some of this automation into solr-operator. Is there an open PR with zk-operator for something new?

**Comment by HoustonPutman** [comment]
There is a PR for adding ephemeral storage and cleaning up the section in their CRD https://github.com/pravega/zookeeper-operator/pull/215. But the other functionality is already there.
