### ISSUE TITLE
Make Liveness and Readiness Checks for Solrcloud Statefulset Configurable

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#126]
**Is your feature request related to a problem? Please describe.**
Right now the liveness and readiness checks are hardcoded. I need some flexibility here when running backups to EFS on AWS. It generates high CPU IO Wait and I need more forgiving thresholds.

**Describe the solution you'd like**
Add to the solrcloud spec interface the different parameters that are currently hardcoded, set defaults to what they are now

**Comment by sepulworld** [comment]
I can work on this one if you want to assign to me.

I think the best spec interface for these settings will be in https://github.com/bloomberg/solr-operator/blob/master/api/v1beta1/solrcloud_types.go#L66 @HoustonPutman sound good to you?

**Comment by HoustonPutman** [comment]
Hey @sepulworld, I think this would be a great change! My only suggestion would be that you make a section in the top level SolrCloudSpec that you put these options under. I think that's what you meant, just wanted to make sure :)

Also @bsankara is the only one who can assign now, since I'm no longer at Bloomberg. He's a great replacement for me though!

**Comment by HoustonPutman** [comment]
@sepulworld Anything else to do here, or is it ok to close?

**Comment by sepulworld** [comment]
Yep! All working fine now 👍
