### ISSUE TITLE
Add a Helm Chart for deploying the Solr Operator

### ISSUE THREAD

**Issue by HoustonPutman** [bloomberg/solr-operator#20]
This could make it easier for people to deploy and upgrade the Solr Operator to their clusters.

**Comment by sepulworld** [comment]
I think since the CRDs are autogenerated it might make best sense to host the helm code and subsequent .tar.gz helm packages inside of this Github repo and enable the 'GitHub Pages' functionality on this repo to serve the Helm charts (see https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417 for how to enable GitHub Pages on a repo and allow it to be a repo for helm charts). We have done something similar with a chart we manage: https://github.com/sepulworld/dinghy-ping-helm-chart

It would be cool if Kubebuilder supported helm chart generation, but it presently doesn't do this directly. (some discussion on that topic here: https://github.com/kubernetes-sigs/kubebuilder/issues/387). But we could probably leverage Make and Kustomize to make it work for us I bet. 💯

**Comment by kcmartin** [comment]
Just an FYI on this issue-- myself and @sepulworld have a WIP Helm chart PR on [Swarup's fork](https://github.com/swarupdonepudi/solr-operator/pull/3) of the Solr Operator
